task: medical
seed: 1

##### data ######

batch_size: 36
num_workers: 3

root: /mnt/data1/MedicalDataset/Kaggle
t_file: ./data/no_normal_large/train_label_combined.csv
v_file: ./data/no_normal_large/valid_label_combined.csv

##### train #####

backbone: densenet

lr: 0.001
momentum: 0.9
weight_decay: 0.0005

lr_gamma: 0.001
lr_decay: 0.75

epochs: 3000

##### pretrain #####

pretrain_model:
pretrain_epoch: 0

##### evaluate #####
validate_per_epoch: 1
threshold: 0.5

finetune: True